### PR TITLE
all: apply Dan Kortschak API modifications

### PR DESCRIPTION
**Pull request by sbinet**
- drop `Location`
- replace with `Identifier`
- drop `_go_hdf5` prefix (internal `Datatype`)

### CODE REVIEW

**Comment by sbinet** [comment]
@kortschak PTAL

**Comment by kortschak** [comment]
Merge this before the import path changes?

**Comment by sbinet** [comment]
SGTM.

are you ok with the commit message?

**Comment by kortschak** [comment]
Yeah, they're fine. Thanks.

**Pull request merged**
